FROM tomcat:latest
MAINTAINER hiono <bps@sculd.com>
LABEL version=@GITBUCKET_VERSION@
ENV DEBIAN_FRONTEND=noninteractive TERM=xterm GITBUCKET_HOME=/var/gitbucket
RUN rm -rf /usr/local/tomcat/webapps/ROOT
Add @DOWNLOAD_URL@ /usr/local/tomcat/webapps/ROOT.war
RUN (cd /usr/local/tomcat/webapps; ln -s ROOT.war gitbucket-@GITBUCKET_VERSION@.war)
RUN mkdir -p $GITBUCKET_HOME/plugins
WORKDIR $GITBUCKET_HOME/plugins
RUN wget -nv -r -A .jar -e robots=off -nd https://github.com/takezoe/gitbucket-gist-plugin/releases
VOLUME $GITBUCKET_HOME
WORKDIR $GITBUCKET_HOME
EXPOSE 8080
EXPOSE 29418
CMD [ "/usr/local/tomcat/bin/catalina.sh", "run" ]
