gitbucket:
  image: lightszentip/gitbucket
  volumes:
   - data:/var/gitbucket
   - gitbucket.conf:/var/gitbucket/gitbucket.conf:ro
  environment:
   GITBUCKET_HOME: "/var/gitbucket"
  expose:
    - "8080"
    - "29418"
